#!/usr/bin/env bash

BASEPATH=$(dirname $0)
INSTALLPATH=~
DOTFILE=.dotfiles

# include
source $BASEPATH/zsh/colors.zsh
source $BASEPATH/zsh/functions.zsh

function initialize {
	printf "################################################################################\n"
	printf "### Dotfiles                                                                 ###\n"
	printf "################################################################################\n"
	touch $INSTALLPATH/$DOTFILE
}

function finalize {
	echo "done" > $INSTALLPATH/$DOTFILE
}

function symlink {
	TEMPLATES=$BASEPATH/**/*.tmpl
	for template in $TEMPLATES; do
		filename=${template/\.tmpl/}
		if [ ! -f $filename ]; then
			progress $template
			symlink=""
			while read line || [[ -n $line ]]; do
				if [[ $line =~ %(.+)% ]]; then
					varname="${BASH_REMATCH[1]}"
					question "Enter value for <${varname}>: "
					read -s varvalue < /dev/tty
					line="${line//%$varname%/$varvalue}"
				fi
				symlink="$symlink$line\n"
			done < $template

			printf "$symlink" > $filename
			success $template
		fi
	done

	SYMLINKS=$BASEPATH/**/*.symlink
	for symlink in $SYMLINKS; do
		filename=${symlink/\.symlink/}
		progress $symlink
		ln -fs $(readlink -f $symlink) $INSTALLPATH/.$(basename $filename)
		success $symlink
	done
}

# run
initialize
symlink
finalize
